config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for(@article) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<%= link_to 'back to list', articles_path%>

app/views/articles/index.html.erb
<div class="container">
  <%@articles.each do |article| %>
    <div class="row mt-2">
      <div class="col-8">
        <div class="article">
          <h2>
            <%=link_to article.title, article_path(article) %>
          </h2>
          <p>
            <%= article.content.byteslice(0, 100)%>...
          </p>
        </div>
      </div>
    </div>
  <%end %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_for(@article) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<%= link_to 'back to list', articles_path%>

app/views/articles/show.html.erb
<div class="container">
  <div class="row mt-2">
    <div class="col-8">
      <div class="article">
        <h2>
          <%=@article.title%>
        </h2>
          <i><%= link_to '', edit_article_path, class: 'fa fa-pencil btn btn-success m-3 p-2' %></i>
          <i><%= link_to '', article_path(@article), method: :delete, class: 'fa fa-trash-o btn btn-danger m-3 p-2' %></i>
        <p>
          <%=@article.content%>...
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default d-flex" role="navigation">
    <div class="container-fluid">
      <a href="/articles">Articles</a>
      <a href="/articles/new">New Article</a>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>